### ISSUE TITLE
Checkbox should use `isEditable` instead of `disabled`

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/components#288]
## 🐛 Bug Report

The way that Checkbox is enabled/disable is not consistent with other components. 

## Expected behavior

Instead of a disabled prop, there should be a isEditable prop.

## Technical Notes
* This will be a breaking change.

## Related Issues
#62 
https://github.com/HospitalRun/hospitalrun/issues/218

**Comment by Alex-IS** [comment]
I would like to take this task.  Also, I guess that expected behavior should be:

 _Instead of a `disabled` prop, there should be a `isEditable` prop._

based on this comment https://github.com/HospitalRun/hospitalrun/issues/218#issuecomment-588557293

Looking forward to start contributing to this project

**Comment by jackcmeyer** [comment]
@Alex-IS welcome!  And yes you’re right, I flipped it. I’ve updated the issue.

**Comment by jackcmeyer** [comment]
@Alex-IS. Forgive me, I really messed this one up. 

The correct implementation should be a disabled prop, so that it's consistent with the rest of the components.

**Comment by Alex-IS** [comment]
No problem :-) Should we implement wrapper component in frontend package?

**Comment by jackcmeyer** [comment]
> No problem :-) Should we implement wrapper component in frontend package?

I think this could be a good idea.

**Comment by Alex-IS** [comment]
Also, what is the reasoning about having wrapper components in frontend package? I'm trying to understand architecture decisions, so I can be of help

**Comment by jackcmeyer** [comment]
The intention of the components repository is for it to be a spot where the most "primitive" components are defined. The advantage is that once the interfaces are defined, then these components can be updated independently without breaking any changes. 

At the time, it felt like the "wrapper" components were not "primitive" enough to be defined in the components repository. However, I think it could (and maybe should) be defined in this repository.
