### ISSUE TITLE
Ability to define actions for a row in the table

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/components#329]
## 🚀 Feature Proposal

Right now, the table component is all data driven. However, often times in a table it is helpful to have a column that has buttons that allows me to do some action based on the data in that row.

## Motivation
* Patient search

## Example
* in the patient's search, I would like a button that allows me to go directly to the edit patient screen.

**Comment by gokhaleprachi** [comment]
Could I work on this?

**Comment by fox1t** [comment]
@gokhaleprachi assigned!

**Comment by kumikokashii** [comment]
Hi, may I take this?

**Comment by kumikokashii** [comment]
Updating the Table component is also covered in the ticket https://github.com/HospitalRun/components/issues/411. Closing this ticket.
