### ISSUE TITLE
Table rows should have the option to be clickable

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/components#330]
## 🚀 Feature Proposal

Often times, when using a table, I want to be able to click on the table row and have it do some action. 

If the table row is clickable: I would expect the following: 
* The hover icon to become a pointer rather than the default curor
* Clicking anywhere in the table row should execute the onClick function. 

## Motivation
* Patient search

## Example
* When I click on the row, I want the Patient search table to bring me to that patient.

**Comment by gokhaleprachi** [comment]
Can I work on this?

**Comment by jackcmeyer** [comment]
go for it @gokhaleprachi!

**Comment by kumikokashii** [comment]
This is a part of the ticket https://github.com/HospitalRun/components/issues/411. Closing.
