### ISSUE TITLE
Add `Callout` component

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/components#487]
## 🚀 Feature Proposal

Add a component called "Callout" to the component library. 

A callout component has the following prop interface:

```ts
interface Props {
	title?: string
	color: 'success' | 'warning' | 'danger' | 'primary' | 'secondary' | 'default
	children?: React.ReactElement,
	className?: string
	style?: CSSProperties 
}
``` 

## Example
From bootstrap docs:
![image](https://user-images.githubusercontent.com/18731800/85914908-7a571d00-b808-11ea-8a8f-6cd289cc20ec.png)

**Comment by nischayv** [comment]
I can take this one!

**Comment by jackcmeyer** [comment]
assigned to you @nischayv

**Comment by nischayv** [comment]
@jackcmeyer While Bootstrap does use it in its docs, doesn't look like it officially supports the component. As a result, react-bootstrap doesn't have it either. Do we still want this component? It would involve stripping the styles from the usage in bootstrap docs and we'd have to maintain it ourselves (Potential future design principle changes from bootstrap would affect it and we'd have to change it accordingly to be consistent with other components - like how material design changed its principles with material 2.0). If it's still a nice to have and potentially useful component I'd be happy to build it! Just wanted to point out the maintainability aspect.

**Comment by jackcmeyer** [comment]
Yeah, I think that we'd still like it. Here is example codepen: https://codepen.io/superjaberwocky/pen/AXdEWj. 

I like this example minus the the colored headings.
