### ISSUE TITLE
Basic authentication prompt

### ISSUE THREAD

**Issue by fox1t** [HospitalRun/components#571]
## 🐛 Bug Report

When a user is logged out (with cleared browser cache) and goes to the index, it is prompted both with basic authentication dialog from the browser before the redirect to the login screen from the app.
<img width="2552" alt="image" src="https://user-images.githubusercontent.com/1620916/91582184-be24ea80-e94f-11ea-8f8b-8832cb6b2dbc.png">

## To Reproduce
Logout, clear the browser cache and navigate to the home.

## Expected behavior
Only the app login screen is presented.

## Your Environment
- _os_: Mac
- browser: chrome, firefox, safari

**Comment by DouglasDev** [comment]
I would like to have a go at this.

**Comment by fox1t** [comment]
Yours!

**Comment by DouglasDev** [comment]
@fox1t I tried my best, but I cannot reproduce the issue. I'm using the latest version of Chrome on Mac. I logged into the local version on localhost:3000 using the default user 'username'. I then clicked 'logout', cleared my browser's cache and cookies, and then navigated to localhost:3000. I was immediately redirected to the login page without seeing the browser authentication pop up. Did I miss any steps.

**Comment by fox1t** [comment]
I don't think so. Can you try a different browser? Have you any chance to install Firefox?

**Comment by DouglasDev** [comment]
Yes I tested in Firefox and it also worked correctly. Could it be that this is caused by your computer being configured in a certain way? For example is your account lacking admin privileges? Might you have certain extra security settings enabled that are causing the system to show the extra dialogue? Are you able to reproduce this issue on other computers?

**Comment by fox1t** [comment]
This issue was present some time ago and then suddenly disappeared. Now it is back but it seems only for me :)

Nothing special on my Macbook, by the way. I'll leave this issue open for a couple of days. After that period of time I am going to close it if no one reports it again.

**Comment by DouglasDev** [comment]
@fox1t Just to make sure, I would like to test on staging.hospitalrun.io. How can I get the login credentials?

**Comment by fox1t** [comment]
username: username
password: password

**Comment by DouglasDev** [comment]
There seems to be an issue with authentication:

<img width="1164" alt="Screen Shot 2020-08-28 at 3 58 51 PM" src="https://user-images.githubusercontent.com/25951701/91610533-6b473500-e947-11ea-8685-5bb57db8eaa0.png">

**Comment by DouglasDev** [comment]
@fox1t So I actually was able to reproduce this issue by changing the api url in shared/config/pouchdb.ts from `${process.env.REACT_APP_HOSPITALRUN_API}/hospitalrun` to https://couchdb.run.hospital so I'm connecting to the staging database from my local machine. When I do this, I see the browser pop up appear repeatedly. However, the issue I'm seeing is maybe slightly different than the one you reported. The pop up keeps appearing even after I'm logged in and when I click cancel, it goes away, but I see the following error in my network tab: `{"error":"unauthorized","reason":"You are not a server admin."}`

**Comment by fox1t** [comment]
@blestab, it is safe to assume that it nginx that is adding a hader.
@tehKapa can you double check this?

**Comment by tehKapa** [comment]
Yes, I also have a similar problem locally. I had to specify `https://couchdb.run.hospital**/hospitalrun**` as env var
