### ISSUE TITLE
Add Billing and Inventory icons

### ISSUE THREAD

**Issue by blestab** [HospitalRun/components#667]
## 🚀 Feature Proposal

We need billing and inventory modules icons.

## Motivation

With the implementation of the basic billing and inventory modules, there is a need for icons for these modules for the menu/navbars.

### Billing
- https://fontawesome.com/icons/hand-holding-usd?style=solid
- https://fontawesome.com/icons/file-invoice-dollar?style=solid
- https://fontawesome.com/icons/money-bill-alt?style=solid

### Inventory 
- https://fontawesome.com/icons/truck-loading?style=solid
- https://fontawesome.com/icons/warehouse?style=solid
- https://fontawesome.com/icons/box-open?style=solid

## Linked Issues:
- [x] Add a billing icon ~HospitalRun/components/issues/668~
- [x] Add an inventory icon ~HospitalRun/components/issues/669~

**Comment by StefanoMiC** [comment]
I would probably go with: 
https://fontawesome.com/icons/file-invoice-dollar?style=solid for Billing 
and https://fontawesome.com/icons/boxes?style=light for Inventory

**Comment by blestab** [comment]
> I would probably go with:
> https://fontawesome.com/icons/file-invoice-dollar?style=solid for Billing
> and https://fontawesome.com/icons/boxes?style=light for Inventory

Awesome!,  thanks @StefanoMiC I'll go ahead and split these into two issues.
