### ISSUE TITLE
Updates README.md

### ISSUE THREAD

**Issue by tehKapa** [HospitalRun/components#9]
Rewrite Spinner example and add new examples for Graph components

**Comment by jackcmeyer** [comment]
@tehKapa are there any options for automating documentation generation for components using tsdx. 

I've used [react-docgen](https://github.com/reactjs/react-docgen) in the past, but I haven't tried it out with tsdx before. 

cc @fox1t

**Comment by tehKapa** [comment]
@jackcmeyer green-light :traffic_light:
